import {StyleSheet} from 'react-native';

export default StyleSheet.create({
    container: {
      flex: 1,
    },
    btnText: {
      fontSize: 30,
      color: 'purple',
      fontWeight: 'bold'
    },
    opText: {
      fontSize: 30,
      fontWeight: '490',
      color: 'red',
    },
    resText: {
      fontSize: 24,
      color: '#1F4690',
    },
    calText:{
      fontSize: 30,
      color: '#1F4690',
    },
    result: {
      flex: 2,
      backgroundColor: '#FEFBF6',
      justifyContent: 'center',
      alignItems: 'flex-end',
      paddingRight: 8,
    },
    calculation: {
      flex: 1,
      backgroundColor: '#FEFBF6',
      justifyContent: 'center',
      alignItems: 'flex-end',
      paddingRight: 8,
    },
    buttons: {
      flexDirection: 'row',
      flex: 8,
    },
    numbers: {
      flex: 3,
      backgroundColor: '#DFE8CC',
    },
    operations2: {
      flex: 1,
      backgroundColor: '#DFE8CC',
      justifyContent: 'space-around',
      alignItems: 'center',
    },
    operations1: {
      flex: 1,
      flexDirection: 'row',
      backgroundColor: '#DFE8CC',
      justifyContent: 'space-around',
      alignItems: 'center',
    },
    btn: {
      flex: 1,
      alignSelf: 'stretch',
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: 'white',
      borderWidth: 3,
      height: 72,
      width: 80,
      borderRadius: 8,
      backgroundColor: 'white',
      margin: 15,
    },
    operations1btn: {
      flex: 1,
      alignSelf: 'stretch',
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: 'white',
      borderWidth: 3,
      height: 72,
      width: 80,
      borderRadius: 8,
      backgroundColor: 'white',
      margin: 15,
    },
    operations2btn: {
      flex: 1,
      alignSelf: 'stretch',
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: 'white',
      borderWidth: 3,
      height: 0,
      width: 70,
      borderRadius: 8,
      backgroundColor: 'white',
      margin: 15,
    },
    row: {
      flexDirection: 'row',
      flex: 1,
      justifyContent: 'space-around',
      alignItems: 'center',
    },
  });
